version: '3'
services:
  saving_simulator:
    container_name: 'saving_simulator'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      "PORT": "8000"
      "DB_ADDRESS": "saving_postgres"
      "DB_PORT": 5432
      "DB_USER": ""
      "DB_PASSWORD": ""
      "DB_DATABASE": ""
      "CACHE_ADDRESS": ""
      "CACHE_PORT":
      "CACHE_DB":
  saving_db:
    container_name: "saving_postgres"
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    environment:
      "POSTGRES_PASSWORD":
      "POSTGRES_USER":
      "POSTGRES_DB":
  saving_cache:
    container_name: "saving_cache"
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  pgdata:
  cache:

